### PR TITLE
Rhodium docs

### PR DESCRIPTION
**Pull request by quaquel**
closing #35

### CODE REVIEW

**Comment by EwoutH** [comment]
I think the content itself is good, but I'm a bit in doubt of it's location. It takes a lot of space on the main page, while it's partly background information. The main page should be about the bare essentials to get up to speed and started.

On the other hand I don't see another obvious place for this information.

**Comment by quaquel** [comment]
I went back and forth on exactly this problem. The alternative I saw would be to add it as a separate entry under getting started. I decided to first write the content and make sure that was on point. 

The advantage of adding it under getting started is that it would be a placeholder for expanding the conversation to other libraries that are not in Python but are similar in scope, like the MORDM framework in R and [OpenMOLE](https://openmole.org).

**Comment by EwoutH** [comment]
Then I think for now this is fine, and in the future we can always reorder it.

**Comment by quaquel** [comment]
I reorganized the comparison to rhodium into its own page. As part of this, I moved all getting started files to their own folder and modified the changelog file to avoid indexing beyond the main page. I think with some minor commit magic this is now ready to be merged

**Comment by quaquel** [comment]
Let me know if I can squash and merge this. I think it is ready and your review comments have been addressed.

**Comment by EwoutH** [comment]
Yeah looks good, sorry for taking so long. The main thing I currently don't like is the Changelog being in two places, that means additional maintenance (at some point we're going to forget updating on or oneother.

Could we link CHANGELOG.md to Read the Docs and remove the other?

**Comment by quaquel** [comment]
The setup should be that we only modify the changelog in the source code. Readthedocs parses this file to create the version within the docs directory. See the code below from conf.py. I want the changelog to be part of the source code that you install so that you can always check it even when not having internet access.

https://github.com/quaquel/EMAworkbench/blob/3f60527b0e392a2edec3971a49ce7cbdd80f6710/docs/source/conf.py#L262-L266

**Comment by EwoutH** [comment]
I like the idea, but I have a few questions about it. Let's discuss it in person at our next meeting.

**Review by EwoutH — APPROVED** [review]

**Pull request merged**
