### PR TITLE
release of version 2.3

### PR DESCRIPTION
**Pull request by quaquel**

### CODE REVIEW

**Comment by EwoutH** [comment]
@quaquel Awesome! I rewrote the changelog a bit, let me know what you think. The rest looks good!

I also added that this is the lastrelease series with Python 3.8 support. I do like to start implementing some type hinting, and having Python 3.9 as minimum version really helps for that. Is that fine by you?

One other thing, we should adres a few of the deprecations (in https://github.com/quaquel/EMAworkbench/issues/201) before release, because the 2.3.0 release series will likely live for quite some time (maybe even half a year). Especially the Sobol deprecation in SALib is coming quite soon.

**Comment by EwoutH** [comment]
Furthermore, do you want to do something with #82 and #102 before release?

**Comment by quaquel** [comment]
We are constrained by what is available on e.g., [DelftBlue](https://www.tudelft.nl/dhpc/system). In general, these systems are slow to adopt new versions. DelftBlue is still on 3.8 and as long as that is not changed, we cannot move forward either.

I'll see what I can do on #82 and #102 over the weekend. Neither one is complicated so it should be nice if those are closed. #201 requires some testing against the 1.4.6 of SALib. 

The fact that 2.4 is likely to come only in spring does not mean that we can do intermediate updates to deal with e.g. depreciation issues.

**Comment by EwoutH** [comment]
They should really go straight for 3.11, that's 20%+ compute time saved right there.

Note that current versions can still keep running on 3.8, the version bump will only apply to the next release.

**Comment by quaquel** [comment]
Any idea when 1.5 of SALib is expected? I am checking 1.4.6 right now but there sobol is not yet available. That is, only with 1.5 will sobol.py become available, but also saltelli.py will then immediately be removed. This means that there is nothing we can do at this point.

**Comment by quaquel** [comment]
>They should really go straight for 3.11, that's 20%+ compute time saved right there.

In my experience, HPC software moves very slowly. There are so many complex interdependencies that have to be managed. This also means that I would not put into the release that 2.3 will be the latest with 3.8 support. 

What does 3.9 offer for type hinting?

**Comment by quaquel** [comment]
Apart from the 3.8 point, the rest of the rewrite looks good.

**Comment by EwoutH** [comment]
> I am checking 1.4.6 right now but there sobol is not yet available.

It should be in it: https://github.com/SALib/SALib/releases/tag/v1.4.6

Let me come back on the Python 3.8 point.

**Comment by EwoutH** [comment]
Perfect, could you cherry-pick a12c819 to a new PR?

**Comment by quaquel** [comment]
I guess we are ready to release this?

We moved the plotting stuff to 2.4, and MESA is not critical. I doubt I will get to it in the coming days so I suggest we move that to 2.4 as well.

**Review by EwoutH — APPROVED** [review]

**Comment by EwoutH** [comment]
Yes, let's release!

I already like that we have [documented this](https://github.com/quaquel/EMAworkbench/blob/master/CONTRIBUTING.md#releases). Do you want to do it?

**Pull request merged**
