### PR TITLE
add `metric` argument to allow for other linkages

### PR DESCRIPTION
**Pull request by mikhailsirenko**

### CODE REVIEW

**Comment by mikhailsirenko** [comment]
A minor tweak to allow for the ward linkage in `clusterer.apply_agglomerative_clustering`

**Review by quaquel — CHANGES_REQUESTED** [review]
Changes are fine, but can you add NumPy doc style documentation?

**Comment by quaquel** [comment]
documentation looks fine this way. Thanks.

**Comment by EwoutH** [comment]
Thanks, feature and docs look good to me!

Do we want to add tests and/or an example (basically why and when p would us this)?

**Comment by quaquel** [comment]
There is a flu_timeseries_cluster.py example for the clustering in general. I don't think we need an additional example. The reference to the scipy documentation should suffice. Clusterer itself is 100% tested, but we currently don't explicitly test for the metrics kwarg. I can see arguments for and against adding test for this. For now, I am fine with merging this.

**Review by quaquel — APPROVED** [review]

**Comment by EwoutH** [comment]
Thanks @mikhailsirenko!

**Pull request merged**
