### PR TITLE
fixes a bug where binomtest fails because of floating point math

### PR DESCRIPTION
**Pull request by quaquel**
see #312

**note:**  had to change the precommit yaml, because the 23.11.0 fails for me

```
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black-jupyter
```

### CODE REVIEW

**Comment by EwoutH** [comment]
Looks good, do we need new/updated tests?

And what's happening with Black?

**Comment by quaquel** [comment]
I'll fix the tests later today (need to do a few other things first)

black error in GitHub 

```
An error has occurred: InvalidManifestError: 
==> File /Users/jhkwakkel/.cache/pre-commit/repoj1wpzd6z/.pre-commit-hooks.yaml
==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, post-rewrite, prepare-commit-msg, push but got: 'pre-commit'
Check the log at /Users/jhkwakkel/.cache/pre-commit/pre-commit.log
```

switching back from 23.11.0 to 23.10.1 solves this message.

**Comment by EwoutH** [comment]
I find the black part weird, because #309, which updated black to 2023.11.0, was merged two days ago and the CI passes on every run.

**Comment by quaquel** [comment]
I'll also try to look into it a bit later today. A quick search so far has not yielded any results

**Comment by EwoutH** [comment]
@inagege could you test if this fixes the bug for you? You can install this branch of the workbench with:
```
pip install -U -e git+https://github.com/quaquel/EMAworkbench@prim_bug#egg=ema-workbench
```

**Comment by inagege** [comment]
@EwoutH I did a few tests, and it worked each time, that is great

**Pull request merged**
