### PR TITLE
readthedocs: Add search ranking and use latest Python version

### PR DESCRIPTION
**Pull request by EwoutH**
Add a ranking which search results should pop up first (proposed docs/source > ema_workbench/examples > ema_workbench > everything else > all models).

This will make sure that the docs pop up on top, then the examples, then the source code, then all other stuff (including tests) and then the included models. Please let know what you think of this ranking.

Some files are also excluded, most notably the data folders.

See [Configuration file v2#search](https://docs.readthedocs.io/en/stable/config-file/v2.html#search)

Also always use latest stable Python version and build a downloadable [htmlzip](https://docs.readthedocs.io/en/stable/config-file/v2.html#formats).

Furthermore, we could consider adding [Search as you type](https://docs.readthedocs.io/en/stable/server-side-search/index.html#search-as-you-type) with the [readthedocs-sphinx-search](https://readthedocs-sphinx-search.readthedocs.io/) extension. Also we might take a look (during the course) on [search analytics](https://docs.readthedocs.io/en/stable/guides/search-analytics.html) to see where we can improve.

### CODE REVIEW

**Review by quaquel — APPROVED** [review]
Looks good and ranking makes sense.

**Comment by EwoutH** [comment]
Thanks!

For me the searching is stuck, both on this PR and the latest stable docs. Does search work for you?

3A7AE1D7-DE62-4848-AEE3-3BBEF5BB26BA

**Comment by EwoutH** [comment]
Good catch!

> edit2: the fix seems to be to include sphinx_rtd_theme>0.5 explicitly in pyproject.toml.

And this again seemed to be caused by https://github.com/readthedocs/readthedocs.org/issues/7858. 

If we look at a [recent build log](https://readthedocs.org/projects/emaworkbench/builds/19994212/), we're currently installing:

```
Collecting sphinx<2
  Downloading Sphinx-1.8.6-py2.py3-none-any.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 150.6 MB/s eta 0:00:00
Collecting sphinx-rtd-theme<0.5
  Downloading sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl (6.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.4/6.4 MB 179.6 MB/s eta 0:00:00
Collecting readthedocs-sphinx-ext<2.3
  Downloading readthedocs_sphinx_ext-2.2.0-py2.py3-none-any.whl (11 kB)
```
But then in the next step, where our optional `docs` dependencies get installed, this is overwritten:
```
Requirement already satisfied: sphinx in /home/docs/checkouts/readthedocs.org/user_builds/emaworkbench/envs/latest/lib/python3.10/site-packages (from ema-workbench==2.4.0.dev0) (1.8.6)
Collecting sphinx
  Downloading sphinx-6.1.3-py3-none-any.whl (3.0 MB)
```
So we get `sphinx>=2` and `sphinx-rtd-theme<0.5`, which aren't compatible with each other.

Let me try to fix that.

**Comment by EwoutH** [comment]
Of course nothing can't be simple.

I will take a better look at this later this week.

**Comment by quaquel** [comment]
I checked the build LOG and we are now installing the correct versions. However, this does not seem to resolve the problem. Reading up on readthedocs, they seem to still prefer using requirements files instead of pyproject.toml. See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html. So, we might give that a try by having a requirements.in and requirements.txt in the docs directory somewhere. See also https://github.com/readthedocs/readthedocs.org/tree/main/requirements for some examples.

**Comment by EwoutH** [comment]
Yeah I also noticed that. Let's see what they think of it upstream: https://github.com/readthedocs/readthedocs.org/pull/9642#issuecomment-1501156907

**Comment by EwoutH** [comment]
Tried following their documentation to the letter, but still doesn't work. This is one of the most stubborn issues I encountered in a long time.

I filed a new issue upstream: https://github.com/readthedocs/readthedocs.org/issues/10263

**Comment by EwoutH** [comment]
I would have liked to cleaned up this PR some more, and test the search ranking some more. Please wait for explicit go ahead for merging, especially after such a convoluted history.

Anyway, glad to have search working again, I will test tomorrow if the search ordering makes sense, and probably open a PR to revert the docs requirements changes.

**Comment by quaquel** [comment]
My mistake. Had github open, saw the e-mail about the search fix, and just clicked merge on the only open pull request without first refreshing Github.

**Pull request merged**
