### PR TITLE
V2 excel

### PR DESCRIPTION
**Pull request by jpn--**
This PR includes the following changes, please feel free to cherry-pick the good ones, esp. if/when my edits are not consistent with other v2 changes you have planned...

* Let Prim work even if the index of the experiments data frame (x) is non-sequential or does not start at 0, and if the dependent variable is the correct size but is the wrong shape (e.g. has extra degenerate dimensions of size 1).

* Excel models can have inputs and outputs be on multiple worksheets of the same workbook.

* DistributedEvaluator class

* Experiments can be performed by zipping over combinations of scenarios/policies/models using the ‘zip_over’ argument, instead of taking the itertools.product across these three interators (valuable for meta-model development, where we want to ignore the difference between scenarios and policies, and sample that space across all these dimensions together)

* robust_optimization can ignore direction-less (e.g. INFO kind) outcomes in the optimization, and add them back in afterwards.  This requires re-evaluating the final set of experiments, which is inefficient, but it’s not obvious to me how to leave non-directional outcomes in the code that is passed to platypus.  There may be a better solution than this, but this works for me for now.

* triangular and pert (beta-pert) distributions for RealParameter (selected because they are still min-max bounded), and bernoulli distributions for integer (bool) parameters, in addition to the uniform/randint default distributions.  

* Add a UniformLHSSampler class that samples from the uniform distribution even when Parameters have non-uniform distributions specified.

* various minor fixes and documentations.

### CODE REVIEW

**Comment by quaquel** [comment]
is the distributed evaluator in this PR identical to the one in PR #39?

**Comment by quaquel** [comment]
Something else. If I read the code correctly, you have several distinct items in this PR

1. Excel Update
2. Dask support
3. Non uniform sampling
4. Zip over
5. load_yaml idea (I would prefer moving this out of excel and make it generic for all models.

Have I missed anything? Going forward, it might be easier for me if you would be able to have separate PR's for each item. I know struggle to disentangle the various pieces of code related to each separate idea. Also, it might be nice to first open an issue with the problem and your suggested solution. Quite a few of the above idea are related to issues I am thinking about. By having an open issue first, we might coordinate the fix. 

thanks again.

**Comment by jpn--** [comment]
> is the distributed evaluator in this PR identical to the one in PR #39?

The distributed evaluator in this is substantially the same as in PR #39, but with a bug fix and updates for the revised logging.

**Comment by jpn--** [comment]
> Something else. If I read the code correctly, you have several distinct items in this PR
> 
> 1. Excel Update
> 2. Dask support
> 3. Non uniform sampling
> 4. Zip over
> 5. load_yaml idea (I would prefer moving this out of excel and make it generic for all models.
> 
> Have I missed anything? 

There is a list in the first comment in this thread.  Hiding and recovering non-directional terms from robust optimization is the main thing missing from your list, but it is very inelegant and I imagine you'll prefer a better solution.  Also, I apologize for the mess; I'm not really a software developer and I have not yet mastered the branches/pull request work flow, but I'm learning as I go.

**Comment by jpn--** [comment]
> In my view this type of functionality should not be part of the class definition. instead having a load_yaml for general model definitions would be a good idea.

When you have finished merging things from this PR, I'll take a crack at a new PR with load_yaml as a general model feature.

**Comment by quaquel** [comment]
No worries, I am in the same situation. I am not a software engineering or computer scientist either. 

So, I have merged already the excel change. The others, I have to look at more closely. 

1. Excel Update, basically done (apart from point 5 below)
2. Dask support
3. Non uniform sampling (high on my list of priorities, but I want something that covers all distributions in numpy.
4. Zip over -- Not sure about this, would love to hear your motivation
5. load_yaml idea (I would prefer moving this out of excel and make it generic for all models.
6. Hiding and recovering non-directional terms from robust optimization -- understand the use case

Would you mind opening a separate issue for each item. Explain the problem you want to address and shortly describe the way in which you fixed it in this PR. It will help me understand the problem you are trying to solve, place the code changes, and creates a space for discussing solutions. 

In the meantime, the V2 branch has been merged back into master. I am close to releasing a first version of V2 on pip

**Comment by quaquel** [comment]
I think virtually all of this is either merged already or available as a separate pull request so closing it for now

**Pull request closed without merging**
